In [1]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
a/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [7]:
b=np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
a+b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
a>b

array([False, False, False, False, False, False, False, False, False,
       False])

In [10]:
a==b

array([False, False, False, False, False, False, False, False, False,
       False])

In [11]:
a[3]

3

In [12]:
a[0]

0

In [13]:
two_d = np.arange(20).reshape((4,5))
two_d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
two_d[0]

array([0, 1, 2, 3, 4])

In [15]:
two_d[0][3]

3

In [16]:
two_d[0,3]

3

In [17]:
two_d[2,2]

12

In [18]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
a[0:4]

array([0, 1, 2, 3])

In [20]:
a[:4]

array([0, 1, 2, 3])

In [21]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
b= list(range(10))
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
c = a[0:4]
c

array([0, 1, 2, 3])

In [24]:
d = b[0:4]
d

[0, 1, 2, 3]

In [25]:
c[0] = 20
d[0] = 20


In [26]:
a[0]

20

In [27]:
b[0]

0

In [28]:
c = a[0:4].copy()
c[0] = 0

In [29]:
c

array([0, 1, 2, 3])

In [30]:
a

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 二维数组切片

In [31]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])