In [1]:
import numpy as np
import random

In [2]:
a = [random.randint(0,10) for i in range(20)]
a

[10, 6, 1, 8, 2, 8, 0, 1, 3, 5, 6, 1, 8, 9, 9, 7, 3, 1, 6, 0]

In [4]:
list(filter(lambda x : x>5, a))

[10, 6, 8, 8, 6, 8, 9, 9, 7, 6]

In [5]:
a

[10, 6, 1, 8, 2, 8, 0, 1, 3, 5, 6, 1, 8, 9, 9, 7, 3, 1, 6, 0]

In [6]:
a = np.array(a)
a

array([10,  6,  1,  8,  2,  8,  0,  1,  3,  5,  6,  1,  8,  9,  9,  7,  3,
        1,  6,  0])

In [7]:
a[a>5]

array([10,  6,  8,  8,  6,  8,  9,  9,  7,  6])

In [8]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [10]:
a[[True,False,False,True]]

array([0, 3])

In [11]:
a[a>5]

array([], dtype=int32)

In [12]:
a = [random.randint(0,10) for i in range(20)]
a = np.array(a)
a

array([10,  3,  1,  8,  7,  1,  9,  1,  9,  6,  4,  4,  6,  7, 10, 10,  5,
        3,  7,  5])

In [14]:
a[(a>5)&(a%2==0)]

array([10,  8,  6,  6, 10, 10])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 11 but corresponding boolean dimension is 20

### 花式索引

In [19]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
a[[1,3,4,6,7]]

array([1, 3, 4, 6, 7])

In [22]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
a[0,2:3]

array([2])

In [27]:
a[[1,3],[1,3]] # 取得是1，1和3，3上的值

array([ 6, 18])

In [28]:
a[[1,3],:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [29]:
a[[1,3],:][:,[1,3]]

array([[ 6,  8],
       [16, 18]])