In [1]:
import numpy as np

In [2]:
abs(-1)

1

In [3]:
a = np.arange(-5,5)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [4]:
abs(a)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [5]:
np.abs(a)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [6]:
abs?

In [9]:
import math
math.sqrt(4)

2.0

In [10]:
math.sqrt(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [11]:
np.sqrt(a)

<ipython-input-11-c2e2b10f3bad>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([       nan,        nan,        nan,        nan,        nan,
       0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [19]:
# int 向0取整（去掉小数点后的数）
print(int(1.6))
print(int(-1.6))

1
-1


In [18]:
# round 向外取整（四舍五入）
print(round(1.6))
print(round(-1.6))

2
-2


In [16]:
# math.ceil 向上取整
print(math.ceil(1.6))
print(math.ceil(-1.6))

2
-1


In [17]:
# math.floor 向下取整
print(math.floor(1.6))
print(math.floor(-1.6))

1
-2


In [20]:
a = np.arange(-5.5, 5.5)
a

array([-5.5, -4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [21]:
np.ceil(a)

array([-5., -4., -3., -2., -1., -0.,  1.,  2.,  3.,  4.,  5.])

In [22]:
np.floor(a)

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [23]:
np.round(a)

array([-6., -4., -4., -2., -2., -0.,  0.,  2.,  2.,  4.,  4.])

In [25]:
np.trunc(a) # 类似int()

array([-5., -4., -3., -2., -1., -0.,  0.,  1.,  2.,  3.,  4.])

In [26]:
np.rint(a) # 和round()一样

array([-6., -4., -4., -2., -2., -0.,  0.,  2.,  2.,  4.,  4.])

In [27]:
np.modf(a) # 返回两个数组：小数部分和整数部分分开

(array([-0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5,  0.5,  0.5]),
 array([-5., -4., -3., -2., -1., -0.,  0.,  1.,  2.,  3.,  4.]))

In [33]:
x, y = np.modf(a)
print(x)
print('-----')
print(y)

[-0.5 -0.5 -0.5 -0.5 -0.5 -0.5  0.5  0.5  0.5  0.5  0.5]
-----
[-5. -4. -3. -2. -1. -0.  0.  1.  2.  3.  4.]


In [34]:
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [35]:
5/a

<ipython-input-35-a19b66976b24>:1: RuntimeWarning: divide by zero encountered in true_divide
  5/a


array([       inf, 5.        , 2.5       , 1.66666667, 1.25      ])

In [36]:
a = np.sqrt(np.arange(-5,5))
a

<ipython-input-36-fbb2892c553c>:1: RuntimeWarning: invalid value encountered in sqrt
  a = np.sqrt(np.arange(-5,5))


array([       nan,        nan,        nan,        nan,        nan,
       0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

浮点特殊值

In [37]:
float("nan")

nan

In [38]:
float("inf") # 比任何一个数都大

inf

In [39]:
b = np.arange(0, 5)
b = b/b
b

<ipython-input-39-aad75e141911>:2: RuntimeWarning: invalid value encountered in true_divide
  b = b/b


array([nan,  1.,  1.,  1.,  1.])

In [40]:
np.isnan(b) # 判断是否是nan值

array([ True, False, False, False, False])

In [41]:
b[np.isnan(b)] # 把b中所有nan选出

array([nan])

In [43]:
b[~(np.isnan(b))] # 把b中所有非nan选出

array([1., 1., 1., 1.])

In [47]:
a = np.array([1,4,6,3,6])
b = np.array([2,4,3,7,5])
np.maximum(a, b)

array([2, 4, 6, 7, 6])

In [48]:
np.minimum(a, b)

array([1, 4, 3, 3, 5])